### ISSUE TITLE
WD My Book Essential decrypting: TypeError: Odd-length string

### ISSUE THREAD

**Issue by glowdyaus** [themaddoctor/linux-mybook-tools#83]
Hi themaddoctor,

Thank you for posting your guide to decrypting the hardware encrypted WD HDD's. My situation fits right in to your solution, my 2TB just stopped connecting and it appears to be a dead USB bridge. It has the Symwave SW6316 chip with no password set. I've installed the latest Ubuntu onto my Apple Mac Mini and closely followed your guide right up to unwrapping the disk encryption key (DEK) and now I've hit a wall with this issue:

~/wd$ ./unwrap.py 'xxd -p -c 40 edek.bin' 'cat kek.hex' > dek0.hex
Traceback (most recent call last):
  File "./unwrap.py", line 31, in <module>
    CIPHER = binascii.unhexlify(sys.argv[1])
TypeError: Odd-length string

Do you have any advice please?  Note - I'm a complete noob to Ubuntu and decrypting. I've only gotten this far through following your guide to the letter, and with a massive dose of googling, so please bear with me if I'm not quick to understand anything. I am just desperate to recover my files off this drive. 
Thank you!

**Comment by themaddoctor** [comment]
You made a typing error. Single quotes need to be left single quotes. Or maybe kek.hex is corrupt.

**Comment by glowdyaus** [comment]
Thank you for your fast reply. First, what key or key combinations give me just the left single quote?  (sorry I'm sure I sound stupid but I've never typed just a single left quote mark like that before).
I have however advanced through - I copy-pasted the command from your pdf and executed it and this is the next message I've received:
$ ./unwrap.py `xxd -p -c 40 edek.bin` `cat kek.hex` > dek0.hex
Traceback (most recent call last):
  File "./unwrap.py", line 33, in <module>
    print binascii.hexlify(aes_unwrap_key(KEK, CIPHER))
  File "./unwrap.py", line 25, in aes_unwrap_key
    " (expected "+hex(iv)+")")
ValueError: Integrity Check Failed: 0x7f791437dfb38aca (expected 0xa6a6a6a6a6a6a6a6L)

Again thanks in advance for your help.

**Comment by glowdyaus** [comment]
themaddoctor:  I've found the key ` - so sorry for the stupid question. No need to answer that now, thanks. (Doh!)
